[package]
name = "qrcode-in-html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markup = "0.12.5"
actix-web = "3.3.3"