apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: baton-ingress
  namespace: baton
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: baton.houseofmoran.io
    http: &http
      paths:
      - path: /
        backend:
          serviceName: view-service
          servicePort: 80
  - host: baton.minikube
    http: *http