apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: event-pubsub
  namespace: baton
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: event-pubsub
  template:
    metadata:
      labels:
        app: event-pubsub
    spec:
      containers:
      - name: event-pubsub
        image: houseofmoran/event-pubsub:1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthcheck/alive
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthcheck/ready
            port: 3000
          initialDelaySeconds: 0
          timeoutSeconds: 1
